### ISSUE TITLE
Missing package.json when running action v1.6.5

### ISSUE THREAD

**Issue by michael-r-elp** [beat-forge/init-beatsaber#39]
With the latest release the action fails saying it's missing the package.json.
see below run
https://github.com/EnderdracheLP/MultiplayerExtensions/actions/runs/11194622215/job/31121362253#step:4:36

**Comment by ChecksumDev** [comment]
This should be fixed as of v1.6.6, will close once confirmed.

**Comment by michael-r-elp** [comment]
Seems to work re-running this action
https://github.com/Goobwabber/MultiplayerCore/actions/runs/11262811422/job/31368979599
I'll close it

**Comment by ChecksumDev** [comment]
It is strange that It still can't find the `package.json`. I'm gonna have to do some local debugging, but the Band-Aid patch works for now!
